  # -*- coding: utf-8 -*-
 """Untitled0.ipynb

 Automatically generated by Colaboratory.

 Original file is located at
https://colab.research.google.com/drive/19H-gjhL4DDE22vzjS279YTzHIt0TK3H3


 class Account:
 def __init__(self, name, balance):
 self._name = name
 self._balance = balance

 @property
 def Name(self):
 return self._name

 def Print(self):
 print(f"Account Holder Name: {self._name}")
 print(f"Account Balance: ${self._balance:.2f}")

 def Withdraw(self, amount):
 if amount > 0 and amount <= self._balance:
 self._balance -= amount
 print(f"Withdrawal successful. New balance: ${self._balance:.2f}")
 else:
 print("Invalid withdrawal amount.")

 def Deposit(self, amount):
 if amount > 0:
 self._balance += amount
 print(f"Deposit successful. New balance: ${self._balance:.2f}")
 else:
 print("Invalid deposit amount.")


 def find_account(accounts, name):
 for account in accounts:
 if account.Name == name:
 return account
 return None


 def main():
 accounts = []

 while True:
 print("\nMenu:")
 print("1. Create Account")
 print("2. Print Account Details")
 print("3. Deposit Money")
 print("4. Withdraw Money")

 print("5. Exit")

 choice = input("Enter your choice (1-5): ")

 if choice == "1":
 account_name = input("Enter account name: ")
 initial_balance = float(input("Enter initial balance: "))
 new_account = Account(account_name, initial_balance)
 accounts.append(new_account)
 print(f"Account with name '{account_name}' and balance
 '{initial_balance}' created successfully.")
 elif choice == "2":
 account_name = input("Enter account name: ")
 account = find_account(accounts, account_name)
 if account:
 account.Print()
 else:
 print("Error: No account with that name.")
 elif choice == "3":
 account_name = input("Enter account name: ")
 account = find_account(accounts, account_name)
 if account:
 amount = float(input("Enter the deposit amount: "))
 account.Deposit(amount)
 else:
 print("Error: No account with that name.")
 elif choice == "4":
 account_name = input("Enter account name: ")
 account = find_account(accounts, account_name)
 if account:
 amount = float(input("Enter the withdrawal amount: "))
 account.Withdraw(amount)
 else:
 print("Error: No account with that name.")
 elif choice == "5":
 print("Exit")
 break
 else:
 print("Invalid choice. Please enter a number between 1 and 5.")


 if __name__ == "__main__":
 main()